# Generated by Django 5.2.6 on 2025-10-14 07:24

import django.db.models.deletion
import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('excerpt', models.TextField(verbose_name='Excerpt')),
                ('content', froala_editor.fields.FroalaField(verbose_name='Content')),
                ('image', models.ImageField(null=True, upload_to='Posts/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data Updated')),
                ('hashed', models.CharField(blank=True, max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_posts', to='news.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['category'], name='news_inform_categor_803578_idx'), models.Index(fields=['created'], name='news_inform_created_c88149_idx')],
            },
        ),
    ]
