# Generated by Django 4.2.25 on 2025-10-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipuRelatoriu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=100)),
                ('deskrisaun', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tipu Relatorius',
            },
        ),
        migrations.CreateModel(
            name='Relatoriu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulu', models.CharField(max_length=200)),
                ('deskrisaun', models.TextField(blank=True)),
                ('arquivu_pdf', models.FileField(upload_to='relatorius/pdfs/')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32)),
                ('tipu_relatoriu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reports.tipurelatoriu')),
            ],
            options={
                'verbose_name_plural': 'Relatorius',
            },
        ),
    ]
